name: Joohee Kwon
author: Victoria
url: https://victoriagjh.github.io
description: Victoria's Development Blog
github: https://github.com/victoriagjh
linkedin: https://www.linkedin.com/in/victoriagjh/
instagram: https://www.instagram.com/vic_cinth/?hl=ko
facebook: https://www.facebook.com/akrso06197.victan
email: akrso06197@naver.com
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "devs"
    values:
      layout: "dev"

remote_theme : victoriagjh/victoriagjh.github.io
