url: https://victoriagjh.github.io
baseurl: /victoriagjh.github.io/

# Site settings
title: Vics Home
email: akrso06197@naver.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Introduce Me
people:
- name: Joohee Kwon
  pic: joohee
  position: Sleep Lover
  social:
    - title: instagram
      url: # https://www.instagram.com/vic_cinth/?hl=ko
    - title: facebook
      url: # https://www.facebook.com/akrso06197.victan
    - title: github
      url: # https://github.com/victoriagjh

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url: https://www.facebook.com/akrso06197.victan
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: https://github.com/victoriagjh

# Postal address (add as many lines as necessary)
address:
  - line: Eunpyeong
  - line: Seoul,Korea

# Build settings
markdown: kramdown
permalink: pretty
